arc-design/arc-theme

common/cinnamon/cinnamon-dark.css
common/cinnamon/cinnamon.css
common/cinnamon/sass/_common.scss

resolves upstream https://i.imgur.com/xps3bIc.mp4
tested cinnamon 3.4.6 on ubuntu 17.10

Resolve jumping cinnamon panel icons - upstream #852

---

README.md
common/cinnamon/cinnamon-dark.css
common/cinnamon/cinnamon.css
common/cinnamon/sass/_common.scss

Upstream PR #788 - This avoids warning messages as margin:auto
is not supported in cinnamon 3.4 and later
favourites section as per picture same before and after.
Tested cinnamon 3.4.6 ubuntu 17.10
unlike GNOME there isn't any versioning restrictions for cinnamon - so README updated instead.

Remove margin:auto from cinnamon menu applet and default theme

---

common/gtk-3.0/3.20/gtk-dark.css
common/gtk-3.0/3.20/gtk-darker.css
common/gtk-3.0/3.20/gtk-solid-dark.css
common/gtk-3.0/3.20/gtk-solid-darker.css
common/gtk-3.0/3.20/gtk-solid.css
common/gtk-3.0/3.20/gtk.css
common/gtk-3.0/3.20/sass/_budgie.scss
common/gtk-3.0/3.20/sass/_colors.scss
common/gtk-3.0/3.20/sass/gtk-dark.scss
common/gtk-3.0/3.20/sass/gtk-darker.scss
common/gtk-3.0/3.20/sass/gtk-solid-dark.scss
common/gtk-3.0/3.20/sass/gtk-solid-darker.scss
common/gtk-3.0/3.20/sass/gtk-solid.scss
common/gtk-3.0/3.20/sass/gtk.scss

This adds a remodelled Arc theming for the Budgie Desktop
Somewhat based on the default Budgie Desktop System Theme, this native Arc version has the following key highlights:
1. Slightly shaded Transparency rather than total transparency
2. Red Notification icon is now a much pleasant and less intrusive Arc selected blue color
3. More transparent MPRIS styling for Raven
4. Panel always defaults to Arc dark; GTK popups default to Arc colour styling (Arc, Arc Darker, Arc Dark)
5. Support for forced dark theming, tray stylising

budgie desktop styling #16

---

common/gtk-3.0/3.20/sass/_applications.scss

I've based this on 2018_01_release ... I presume this will be merged to master on release?
Mate screensaver styling before (i.e. not themed)
after the patch it is now arc-styled

Mate screensaver styling

---

common/gnome-shell/3.18/sass/_common.scss

I fixed the problem #46 now the text in the top bar of gnome is white

fix color top bar gnome in gnome-shell

---

common/cinnamon/sass/_common.scss

I've only tested this by editing the css files directly but I'm 99% sure I got this right in this pull request. Please test before merging...

fix bouncing launcher icons in cinnamon (again)

---

common/gtk-3.0/3.20/sass/_budgie.scss

1. The Workspace switcher had some weird coloring due to it being a panel applet and getting the light styling but since its actually visible on the panel it should inherent the colors of the panel.
2. The top Raven buttons had no padding to the top panel, which looked weird because they were directly under the panel, which in my opinion is not visually appealing.

Budgie improvements

---

common/gtk-3.0/3.18/sass/_applications.scss
common/gtk-3.0/3.20/sass/_applications.scss

See details in nav_button_provider_gtk3.cc of Chromium source.
Those titlebutton sizes should be equal to Gtk.IconSize.MENU if
Gtk+ themes provided the customed titlebutton icon images.
* Set min-width/height as 16px without any padding.
* Move CSD-titlebutton horizontal spacing from padding to outer margins.
This should fix the issue: #62

Add a workaround for Chrome(ium) CSD-mode titlebuttons (#62)

---

common/gnome-shell/3.18/sass/_common.scss

.overview-icon class contained in .app-well-app has the 1px hidden border
via %icon_tile, but .overview-icon contained in ".show-apps" did not.
I think that might cause some unwanted .show-apps-icon shifting
(mis-alignment). So I added that border in case .show-apps class was
contained by #dashtodockContainer.
This should fix the issue #33.

Add missing 1px hidden border for finer .show-apps-icon alignment

---

README.md

This really confused me when trying to install the theme.

Fix: incorrect autogen.sh parameter name in README

---

common/gtk-3.0/3.20/sass/_applications.scss

Scaled down Thunar navigation icons (please see screenshots)

---

README.md

I'm on Ubuntu 16.04. There are warning output in here
```shell
Rendering assets/arrow-down.png
./render-assets.sh: line 25: /usr/bin/optipng: No such file or directory
Rendering assets-dark/arrow-down.png
./render-assets.sh: line 36: /usr/bin/optipng: No such file or directory
```
It seems that `optipng` is not installed by default in Ubuntu. In the README file, you may have to add it in manual installation

Add optipng package in manual installation

---

common/gnome-shell/3.18/common-assets/switch/switch-off-selected.svg
common/gnome-shell/3.18/common-assets/switch/switch-on-selected.svg
common/gnome-shell/3.18/light-assets/checkbox/checkbox-checked-focused.svg
common/gnome-shell/3.18/light-assets/checkbox/checkbox-checked.svg
common/gnome-shell/3.18/light-assets/misc/message-close-active.svg
common/gnome-shell/3.18/light-assets/switch/switch-on.svg

I think it is pretty self-explanatory, it affected only the light theme
Before
After

Fix gnome-shell switches and checkboxes

---

common/gtk-3.0/3.18/sass/_common.scss

Fix mismatched "}" for GNOME 3.18 NEW

---

common/gtk-3.0/3.18/sass/_applications.scss

This should hopefully fix any of those MATE padding issues that I've been experiencing, although there might have been some update that fixed them on MATE's end (I'm not sure, as I still encounter it with other systems running what I think is the same version.) 
Anyway, I just copied the padding settings over from the gtk 3.20 side, and after a quick test it runs on my Linux Mint 18.3 MATE machine without weird padding problems. Not sure about other DE's as I run exclusively MATE.

Fixing MATE panel icon spacing issues.

---

README.md

As requested in #107, I've created some FirefoxColor themes that match our theme and added the links to README. I personally don't use them, but since it doesn't cost anything, why not?
Feel free to try them and point out if we should modify something

Add link to FirefoxColor themes to README

---

HACKING.md
common/gtk-3.0/3.20/render-asset.sh

Unless someone can think of a good reason,  I don't think there is any need to keep rendering GTK+3 assets all the time i.e. once generated then skip the generation.
Speeds up development.

No need to keep rendering GTK+3 assets

---

common/gtk-3.0/3.20/sass/_applications.scss

A top border was added to the sidebar in Thunar by commit [7c117440c6d2a217f7055a60b3a223585e0f53a2](https://github.com/xfce-mirror/thunar/commit/7c117440c6d2a217f7055a60b3a223585e0f53a2), causing a white top border when using Arc-darker.
I don't know if the application specific fix in this pull request is a correct one. Or should this be fixed somewhere around __common.scss:141?
Result:

Fix thunar sidebar top border color

---

README.md
m4/arc-gnome-shell.m4
m4/arc-gtk3.m4

This updates dependency information in README regarding gnome-shell and gtk3 version auto-detection, and also improves error output from autoconf macros when autodetection fails.
English isn't my first language, so it's possible the grammar could be improved. Let me know if something seems funny, or could be explained clearer.
Hopefully this prevents user confusion, such as in #136

Update documentation for gtk3, gnome-shell and parallel dependencies

---

common/gnome-shell/3.30/sass/_common.scss

Closes https://github.com/NicoHood/arc-theme/issues/135
Workaround the glitch described in #135 by not using svg assets in `border-image` for drawing the `popup-sub-menu` backgrounds, but use plain css instead.
Unfortunately this isn't 100% pixel-perfect workaround, since the text in menu items inside popup-sub-menus is moved 4px right. However I think that wasn't aligned with anything, so the change should be barely noticeable, as seen with "Turn Off" and "Wired Settings" labels below.
Before:
After:
Apart from the text align, everything should look exactly as it did before this change.

Workaround gnome-shell 3.30 popup-sub-menu glitch

---

common/gtk-3.0/3.20/sass/_applications.scss

Properly theme the redesigned path-bar in nautilus 3.30, as discussed in #133.
Closes #133 and #139

Nautilus 3.30 path-bar redesign

---

common/cinnamon/sass/_common.scss
common/gtk-3.0/3.20/sass/_applications.scss

This should fix the missing style for Nemo's floating bar and add spacing to Cinnamon theme to make it look nicer.
Before:
After:

Some fixes for Cinnamon

---

common/gnome-shell/3.30/sass/_common.scss

Fixes #105
---
Before this patch:
After this patch:

Harmonize font-size to 10pt overall Gnome Shell for 3.30

---

common/gtk-3.0/3.20/sass/_common.scss

Steppers are disabled by default but the icons nevertheless get overridden in the css, causing issues to those re-enabling them due to incorrect icon names being used for the horizontal steppers.

Fix horizontal stepper icons (GTK3)

---

common/gtk-3.0/3.18/sass/_applications.scss
common/gtk-3.0/3.20/sass/_applications.scss

Hi,
This PR distinguishes the inactive pane in nemo dual pane mode by using the insensitive fg text color for that pane. In screenshots below the left pane is active.
Before
After

Nemo - distinguish inactive pane in dual pane mode.

---

common/cinnamon/sass/_common.scss

Hi,
Some fixes to the Cinnamon Calendar to better align week numbers and dates.
Before
After
Also it maintains the alignment if users use text scaling values different from 1.

Cinnamon - calendar alignment improvements

---

common/cinnamon/sass/_common.scss

Hi,
This fixes an issue where the selection highlight on the Cinnamon popupmenu overlays the border image creating a bleeding effect. I've also added a visible popupmenu seperator. I think this does look better on larger more complex popup menus.
Before
After

Cinnamon popupmenu

---

common/cinnamon/sass/_common.scss

Cinnamon4 menu - make 'fake' separator arc blue for consistency with older Cinnamon versions

---

common/gtk-3.0/3.20/sass/_common.scss

The horizontal levelbar auto-width and auto-height values were used wrongly for vertical levelbar and vis versa. This lead to a visual minimum load of vertical or and horizontal levelbars.

Fix vertical and horizontal levelbar values

---

common/cinnamon/sass/_common.scss

As per discussion https://github.com/NicoHood/arc-theme/pull/190

Cinnamon - use borders_color for popup-menu seperator

---

common/cinnamon/sass/_common.scss

This removes the hard-coded height from the Cinnamon menu search box so it can expand if necessary for users who use a font-scaling option for accessibility purposes. It doesn't result in any change at regular font scaling settings.
Before
After

Cinnamon menu - fix search entry not expanding for scaled font sizes

---

common/gnome-shell/3.26/sass/_common.scss
common/gnome-shell/3.30/sass/_common.scss

Reverts NicoHood/arc-theme#175
With regards to GNOME pulling dynamic transparency - lets revert the original commit.

Revert "Add GNOME panel dynamic transparency"

---

common/gnome-shell/3.30/sass/_common.scss

Fixes the ugly close buttons in the GNOME overview introduced with the GNOME 3.32 update.
Before:
After:

Fix close buttons in GNOME overview

---

common/gnome-shell/3.30/sass/_common.scss

Fix Gnome shell calendar with 10pt font

---

common/gtk-2.0/dark/assets.svg

#button-insensitive is using `#3e4351` where the correct colour seems to be `#3e4350`

Correct GTK2 dark assets.svg #3e4351 -> #3e4350

---

common/gnome-shell/3.18/common-assets/misc/message-icon.svg
common/gnome-shell/3.30/sass/_colors.scss
common/gnome-shell/3.30/sass/_common.scss

Fixes issues with display scaling greater than 100% (#236) for the following elements:
- Modal dialogs
- Panel button dropdown menus
- OSD popups
- Notifications
- Window switcher
- Workspace switcher
- Looking glass
Essentially, replaces `border-image` CSS properties with `box-shadow` properties.
A couple of quirks:
- Can't seem to get the box shadow to display on left/top sides of panel button dropdown menus and modal dialogs
- Buttons on modal dialogs are not transparent (no way to achieve this without a border image (which doesn't scale correctly, leaving buttons mis-aligned)
Posted screenshots in the issue comment thread. Would be great if someone could test this to confirm that there are no issues with display scaling.
EDIT: this PR also fixes the issue with panel button dropdown …

Remove gnome shell border images

---

common/gnome-shell/3.30/sass/_common.scss

Follow up to #240, fixes a small visual glitch where the corners of panel button dropdown menus were not properly rounded

Fix gnome shell panel menu corner radius

---

common/gnome-shell/3.30/sass/_common.scss

Just realized that the GNOME 3.32 update also messed up the page indicators in the gnome shell applications overview.
This PR goes back to the original Arc appearance for the page indicators:
Gnome 3.32             |  Fixed
----------------------|-------------------------

Fix gnome shell overview page indicator

---

common/gnome-shell/3.30/sass/_common.scss

Make the user pic round in logout (end session) and polkit dialogs, in keeping with GNOME 3.32 styling

Round user icons in GNOME dialogs

---

common/gtk-3.0/3.18/sass/_common.scss
common/gtk-3.0/3.20/sass/_common.scss

cherry-pick from https://github.com/jnsh/arc-theme - primarily to resolve #238 
Note https://github.com/jnsh/arc-theme/commit/b4922180f3335cb17493ffb21a2fdf40e0f2ad33 needed to be cherry-picked to allow the CSD commit to be also cherry-picked

GSD and headerbar transparency

---

common/gnome-shell/3.30/sass/_common.scss

Courtesy of the [Plata theme](https://gitlab.com/tista500/plata-theme), found a solution to render proper drop shadow around gnome shell panel button dropdown menus. Testing welcome ....

Add full shadows to GNOME shell panel button dropdown menus

---

common/gtk-3.0/3.20/sass/_applications.scss

Three fixups for xfce 4.14:
Original PR: (https://github.com/jnsh/arc-theme/pull/11, https://github.com/jnsh/arc-theme/pull/10)
- The font-weight of the taskbar changed:
**Old (xfce4.12)**
**New (xfce4.14)**
**New (xfce4.14) with PR**
- Ugly border around the systray with 'show frame' enabled:
**Old (xfce4.12)**
**New (xfce4.14)**
**New (xfce4.14) with PR**
- Since xfce 4.14 the 'Window Buttons' panel visuals are 'broken' if the 'show flat buttons' option is not enabled.
This setting used to have no effect on the visuals on 4.12.
Old situation (xfce4-panel 4.12 - flat enabled):
Old situation (xfce4-panel 4.12 - flat disabled):
Broken (xfce4-panel 4.14 - flat disabled):
New (xfce4-panel 4.14 with this PR - flat enabled):
New (xfce4-panel 4.14 with this PR - flat disabled):

Xfce4-panel 4.14 fixes
